2023-11-28 20:55:06,557 ERROR: Exception on /contact [POST] [in /home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/app/main_pages/routes.py", line 35, in contact_page
    email_server(form)
  File "/home/alex/production_projects/makeup_artist_website/app/main_pages/mailer.py", line 46, in email_server
    with smtplib.SMTP(host=host, port=port) as server:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-11-28 21:28:48,961 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:17:21,584 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:18:08,643 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:22:04,655 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:28:40,083 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:29:47,817 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:30:20,216 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:30:49,291 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:31:27,288 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:32:05,018 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:34:54,310 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-11-30 12:35:08,448 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/__init__.py:54]
2023-12-02 20:23:28,585 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-02 20:24:23,367 ERROR: Exception on /contact [POST] [in /home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/app/main_pages/routes.py", line 35, in contact_page
    email_server(form)
  File "/home/alex/production_projects/makeup_artist_website/app/main_pages/mailer.py", line 46, in email_server
    with smtplib.SMTP(host=host, port=port) as server:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-12-02 21:32:47,660 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-02 21:33:02,505 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-02 21:38:05,098 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-02 21:44:50,804 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-02 21:46:47,580 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-02 21:51:32,728 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-02 21:54:27,637 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-02 21:54:43,857 ERROR: Exception on /contact [POST] [in /home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/venv/lib/python3.11/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/production_projects/makeup_artist_website/app/main_pages/routes.py", line 35, in contact_page
    email_server(form)
  File "/home/alex/production_projects/makeup_artist_website/app/main_pages/mailer.py", line 46, in email_server
    with smtplib.SMTP(host=host, port=port) as server:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 255, in __init__
    (code, msg) = self.connect(host, port)
                  ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 341, in connect
    self.sock = self._get_socket(host, port, self.timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/smtplib.py", line 312, in _get_socket
    return socket.create_connection((host, port), timeout,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution
2023-12-03 14:57:09,404 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-03 16:16:30,867 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
2023-12-03 16:18:03,629 INFO: Website startup [in /home/alex/production_projects/makeup_artist_website/app/app.py:45]
